spring:
  application:
    name: tencent-add-article-mcp-server
  main:
    web-application-type: none
    banner-mode: off
  ai:
    mcp:
      server:
        name: tencent-add-article-mcp-server
        version: 0.0.3
        stdio: true

logging:
  pattern:
    console:
  file:
    name: data/log/${spring.application.name}.log

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

# 腾讯云开发者社区 API 配置
tencent:
  api:
    # 请配置你的腾讯云开发者社区 Cookie
    # 可以通过以下方式配置：
    # 1. 环境变量: TENCENT_API_COOKIE
    # 2. 本地配置文件: application-local.yml (不会被提交到Git)
    # 3. 系统属性: -Dtencent.api.cookie=your_cookie
    cookie: ${TENCENT_API_COOKIE:请配置你的Cookie}